<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\AbstractMySQLPlatform; use Doctrine\DBAL\Schema\Schema; use Doctrine\Migrations\AbstractMigration;
final class Version20260821060000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add participant, team and external organization registries'; }
    public function isTransactional(): bool { return false; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform, 'MariaDB/MySQL is required.');
        $this->addSql("ALTER TABLE tenants ADD participant_registry_enabled TINYINT(1) DEFAULT 0 NOT NULL, ADD team_registry_enabled TINYINT(1) DEFAULT 0 NOT NULL");
        $this->addSql(<<<'SQL'
CREATE TABLE external_organizations (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, public_id VARCHAR(36) NOT NULL, name VARCHAR(180) NOT NULL, organization_type VARCHAR(24) NOT NULL, city VARCHAR(120) DEFAULT NULL, country_code CHAR(2) DEFAULT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, UNIQUE INDEX uniq_external_org_public (public_id), UNIQUE INDEX uniq_external_org_name (tenant_id, name), UNIQUE INDEX uniq_external_org_tenant_id (tenant_id, id), CONSTRAINT fk_external_org_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE participant_registry (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, public_id VARCHAR(36) NOT NULL, organization_id BIGINT DEFAULT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, birth_date DATE DEFAULT NULL, birth_year SMALLINT DEFAULT NULL, gender VARCHAR(24) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, nationality CHAR(2) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(60) DEFAULT NULL, external_id VARCHAR(120) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, UNIQUE INDEX uniq_participant_registry_public (public_id), UNIQUE INDEX uniq_participant_registry_tenant_id (tenant_id, id), INDEX idx_participant_registry_name (tenant_id, last_name, first_name), CONSTRAINT fk_participant_registry_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE, CONSTRAINT fk_participant_registry_org FOREIGN KEY (organization_id) REFERENCES external_organizations (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE team_registry (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, public_id VARCHAR(36) NOT NULL, organization_id BIGINT DEFAULT NULL, name VARCHAR(180) NOT NULL, category VARCHAR(120) DEFAULT NULL, contact_name VARCHAR(180) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, contact_phone VARCHAR(60) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, UNIQUE INDEX uniq_team_registry_public (public_id), UNIQUE INDEX uniq_team_registry_tenant_id (tenant_id, id), INDEX idx_team_registry_name (tenant_id, name), CONSTRAINT fk_team_registry_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE, CONSTRAINT fk_team_registry_org FOREIGN KEY (organization_id) REFERENCES external_organizations (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE event_participants (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, event_id INT NOT NULL, registry_participant_id BIGINT DEFAULT NULL, public_id VARCHAR(36) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, birth_date DATE DEFAULT NULL, birth_year SMALLINT DEFAULT NULL, gender VARCHAR(24) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, organization_name VARCHAR(180) DEFAULT NULL, external_id VARCHAR(120) DEFAULT NULL, sport_data JSON NOT NULL, anonymized_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, UNIQUE INDEX uniq_event_participant_public (public_id), UNIQUE INDEX uniq_event_participant_tenant_id (tenant_id, id), UNIQUE INDEX uniq_event_participant_scope_id (tenant_id, event_id, id), INDEX idx_event_participant_event (tenant_id, event_id), CONSTRAINT fk_event_participant_event FOREIGN KEY (tenant_id, event_id) REFERENCES events (tenant_id, id) ON DELETE CASCADE, CONSTRAINT fk_event_participant_registry FOREIGN KEY (registry_participant_id) REFERENCES participant_registry (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE event_teams (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, event_id INT NOT NULL, registry_team_id BIGINT DEFAULT NULL, public_id VARCHAR(36) NOT NULL, team_number INT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, organization_name VARCHAR(180) DEFAULT NULL, category VARCHAR(120) DEFAULT NULL, contact_name VARCHAR(180) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, contact_phone VARCHAR(60) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, UNIQUE INDEX uniq_event_team_public (public_id), UNIQUE INDEX uniq_event_team_number (tenant_id, event_id, team_number), UNIQUE INDEX uniq_event_team_tenant_id (tenant_id, id), UNIQUE INDEX uniq_event_team_scope_id (tenant_id, event_id, id), CONSTRAINT fk_event_team_event FOREIGN KEY (tenant_id, event_id) REFERENCES events (tenant_id, id) ON DELETE CASCADE, CONSTRAINT fk_event_team_registry FOREIGN KEY (registry_team_id) REFERENCES team_registry (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
        $this->addSql(<<<'SQL'
CREATE TABLE event_team_memberships (id BIGINT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, event_id INT NOT NULL, team_id BIGINT NOT NULL, participant_id BIGINT NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX uniq_event_participant_team (tenant_id, event_id, participant_id), INDEX idx_membership_team (tenant_id, event_id, team_id), CONSTRAINT fk_membership_event FOREIGN KEY (tenant_id, event_id) REFERENCES events (tenant_id, id) ON DELETE CASCADE, CONSTRAINT fk_membership_team FOREIGN KEY (tenant_id, event_id, team_id) REFERENCES event_teams (tenant_id, event_id, id) ON DELETE CASCADE, CONSTRAINT fk_membership_participant FOREIGN KEY (tenant_id, event_id, participant_id) REFERENCES event_participants (tenant_id, event_id, id) ON DELETE CASCADE, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB
SQL);
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE event_team_memberships'); $this->addSql('DROP TABLE event_teams'); $this->addSql('DROP TABLE event_participants'); $this->addSql('DROP TABLE team_registry'); $this->addSql('DROP TABLE participant_registry'); $this->addSql('DROP TABLE external_organizations'); $this->addSql('ALTER TABLE tenants DROP participant_registry_enabled, DROP team_registry_enabled'); }
}
