<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;use Doctrine\DBAL\Schema\Schema;use Doctrine\Migrations\AbstractMigration;
final class Version20260821070000 extends AbstractMigration
{
 public function getDescription():string{return 'Add complete running event categories, timing and finals model';}public function isTransactional():bool{return false;}
 public function up(Schema $schema):void{$this->abortIf(!$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform,'MariaDB/MySQL is required.');
 $this->addSql("CREATE TABLE running_event_settings (event_id INT NOT NULL, tenant_id INT NOT NULL, qualification_runs SMALLINT UNSIGNED DEFAULT 2 NOT NULL, finalists_per_category SMALLINT UNSIGNED DEFAULT 3 NOT NULL, time_precision VARCHAR(20) DEFAULT 'tenths' NOT NULL, final_enabled TINYINT(1) DEFAULT 1 NOT NULL, finalists_confirmed_at DATETIME DEFAULT NULL, finalists_confirmed_by_user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, lock_version INT DEFAULT 1 NOT NULL, CONSTRAINT fk_running_settings_event FOREIGN KEY (tenant_id,event_id) REFERENCES events (tenant_id,id) ON DELETE CASCADE, CONSTRAINT fk_running_settings_user FOREIGN KEY (finalists_confirmed_by_user_id) REFERENCES tenant_users (id) ON DELETE RESTRICT, PRIMARY KEY(event_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
 $this->addSql("CREATE TABLE running_categories (id BIGINT AUTO_INCREMENT NOT NULL,tenant_id INT NOT NULL,event_id INT NOT NULL,public_id VARCHAR(36) NOT NULL,name VARCHAR(120) NOT NULL,birth_year_from SMALLINT NOT NULL,birth_year_to SMALLINT NOT NULL,gender VARCHAR(24) NOT NULL,sort_order INT DEFAULT 0 NOT NULL,active TINYINT(1) DEFAULT 1 NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,lock_version INT DEFAULT 1 NOT NULL,UNIQUE INDEX uniq_running_category_public(public_id),UNIQUE INDEX uniq_running_category_definition(tenant_id,event_id,birth_year_from,birth_year_to,gender),UNIQUE INDEX uniq_running_category_scope(tenant_id,event_id,id),CONSTRAINT fk_running_category_event FOREIGN KEY(tenant_id,event_id) REFERENCES events(tenant_id,id) ON DELETE CASCADE,PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
 $this->addSql("CREATE TABLE running_participant_data (participant_id BIGINT NOT NULL,tenant_id INT NOT NULL,event_id INT NOT NULL,category_id BIGINT DEFAULT NULL,start_number INT UNSIGNED NOT NULL,finalist_confirmed TINYINT(1) DEFAULT 0 NOT NULL,final_start_order SMALLINT UNSIGNED DEFAULT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,lock_version INT DEFAULT 1 NOT NULL,UNIQUE INDEX uniq_running_start_number(tenant_id,event_id,start_number),INDEX idx_running_participant_category(tenant_id,event_id,category_id),CONSTRAINT fk_running_participant FOREIGN KEY(tenant_id,event_id,participant_id) REFERENCES event_participants(tenant_id,event_id,id) ON DELETE CASCADE,CONSTRAINT fk_running_participant_category FOREIGN KEY(category_id) REFERENCES running_categories(id) ON DELETE SET NULL,PRIMARY KEY(participant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
 $this->addSql("CREATE TABLE running_qualification_results (id BIGINT AUTO_INCREMENT NOT NULL,tenant_id INT NOT NULL,event_id INT NOT NULL,participant_id BIGINT NOT NULL,run_number SMALLINT UNSIGNED NOT NULL,time_units INT UNSIGNED DEFAULT NULL,status VARCHAR(16) NOT NULL,notes VARCHAR(500) DEFAULT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,lock_version INT DEFAULT 1 NOT NULL,UNIQUE INDEX uniq_running_qualification(tenant_id,event_id,participant_id,run_number),CONSTRAINT fk_running_qualification_participant FOREIGN KEY(tenant_id,event_id,participant_id) REFERENCES event_participants(tenant_id,event_id,id) ON DELETE CASCADE,PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
 $this->addSql("CREATE TABLE running_final_results (participant_id BIGINT NOT NULL,tenant_id INT NOT NULL,event_id INT NOT NULL,time_units INT UNSIGNED DEFAULT NULL,status VARCHAR(16) NOT NULL,notes VARCHAR(500) DEFAULT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,lock_version INT DEFAULT 1 NOT NULL,CONSTRAINT fk_running_final_participant FOREIGN KEY(tenant_id,event_id,participant_id) REFERENCES event_participants(tenant_id,event_id,id) ON DELETE CASCADE,PRIMARY KEY(participant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");}
 public function down(Schema $schema):void{$this->addSql('DROP TABLE running_final_results');$this->addSql('DROP TABLE running_qualification_results');$this->addSql('DROP TABLE running_participant_data');$this->addSql('DROP TABLE running_categories');$this->addSql('DROP TABLE running_event_settings');}
}
