<?php
declare(strict_types=1);
namespace App\Core\Presentation\Web\Controller\Tenant;
use App\Core\Application\Event\CsvImportService; use App\Core\Application\Event\ParticipantTeamService; use App\Core\Infrastructure\Doctrine\Entity\TenantUser; use App\Core\Infrastructure\Tenancy\TenantContext; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\Request; use Symfony\Component\HttpFoundation\Response; use Symfony\Component\Routing\Attribute\Route;
final class EventRosterController extends AbstractController
{
    #[Route('/v/{slug}/veranstaltungen/{id}/meldungen',name:'tenant_event_roster',methods:['GET','POST'])]
    public function index(string $id,Request $request,TenantContext $context,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser){throw $this->createAccessDeniedException();}$error=null;if($request->isMethod('POST')){if(!$this->isCsrfTokenValid('event_roster_'.$id,$request->request->getString('_token'))){throw $this->createAccessDeniedException();}try{match($request->request->getString('action')){'participant'=>$service->addEventParticipant($user,$id,$request->request->all(),$request->getClientIp()??''),'team'=>$service->addEventTeam($user,$id,$request->request->all(),$request->getClientIp()??''),'assign'=>$service->assignTeam($user,$id,$request->request->getString('participant'),$request->request->getString('team'),$request->getClientIp()??''),default=>throw new \DomainException('Unbekannte Aktion.')};return $this->redirectToRoute('tenant_event_roster',['slug'=>$context->get()->getSlug(),'id'=>$id]);}catch(\DomainException $e){$error=$e->getMessage();}}return $this->render('tenant/events/roster.html.twig',['tenant'=>$context->get(),'roster'=>$service->roster($user,$id),'error'=>$error]);}
    #[Route('/v/{slug}/veranstaltungen/{id}/csv-vorlage',name:'tenant_event_csv_template',methods:['GET'])]
    public function template(string $id,CsvImportService $csv,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser){throw $this->createAccessDeniedException();}$service->roster($user,$id);return new Response($csv->template(),200,['Content-Type'=>'text/csv; charset=UTF-8','Content-Disposition'=>'attachment; filename="lauf-teilnehmer.csv"']);}
    #[Route('/v/{slug}/veranstaltungen/{id}/csv-vorschau',name:'tenant_event_csv_preview',methods:['POST'])]
    public function preview(string $id,Request $request,TenantContext $context,CsvImportService $csv,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser||!$this->isCsrfTokenValid('event_csv_'.$id,$request->request->getString('_token'))){throw $this->createAccessDeniedException();}$service->roster($user,$id);$file=$request->files->get('csv');if($file===null||!$file->isValid()||($file->getSize()??0)>2_000_000||mb_strtolower($file->getClientOriginalExtension())!=='csv'){throw new \DomainException('Bitte eine gültige CSV-Datei bis 2 MB hochladen.');}$preview=$csv->preview($file->getContent());$request->getSession()->set('event_csv_'.$id,$preview);return $this->render('tenant/events/csv_preview.html.twig',['tenant'=>$context->get(),'event_id'=>$id,'preview'=>$preview]);}
    #[Route('/v/{slug}/veranstaltungen/{id}/csv-fehler',name:'tenant_event_csv_errors',methods:['GET'])]
    public function errors(string $id,Request $request,CsvImportService $csv,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser){throw $this->createAccessDeniedException();}$service->roster($user,$id);$preview=$request->getSession()->get('event_csv_'.$id);$errors=is_array($preview)&&isset($preview['errors'])&&is_array($preview['errors'])?$preview['errors']:[];return new Response($csv->errorReport($errors),200,['Content-Type'=>'text/csv; charset=UTF-8','Content-Disposition'=>'attachment; filename="csv-fehler.csv"']);}
    #[Route('/v/{slug}/veranstaltungen/{id}/csv-import',name:'tenant_event_csv_import',methods:['POST'])]
    public function import(string $id,Request $request,TenantContext $context,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser||!$this->isCsrfTokenValid('event_csv_import_'.$id,$request->request->getString('_token'))){throw $this->createAccessDeniedException();}$preview=$request->getSession()->remove('event_csv_'.$id);if(!is_array($preview)||!isset($preview['valid'])||!is_array($preview['valid'])){throw new \DomainException('CSV-Vorschau ist abgelaufen.');}$imported=0;$strategy=$request->request->getString('duplicates','skip');foreach($preview['valid'] as $row){if(is_array($row)&&$service->importCsvParticipant($user,$id,$row,$strategy,$request->getClientIp()??'')){++$imported;}}$this->addFlash('success',$imported.' gültige Zeilen importiert oder aktualisiert.');return $this->redirectToRoute('tenant_event_roster',['slug'=>$context->get()->getSlug(),'id'=>$id]);}
}
