<?php
declare(strict_types=1);
namespace App\Core\Presentation\Web\Controller\Tenant;
use App\Core\Application\Event\ParticipantTeamService; use App\Core\Infrastructure\Doctrine\Entity\TenantUser; use App\Core\Infrastructure\Tenancy\TenantContext; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\Request; use Symfony\Component\HttpFoundation\Response; use Symfony\Component\Routing\Attribute\Route;
final class RegistriesController extends AbstractController
{
    #[Route('/v/{slug}/stammdaten',name:'tenant_registries',methods:['GET','POST'])]
    public function index(Request $request,TenantContext $context,ParticipantTeamService $service):Response { $user=$this->getUser();if(!$user instanceof TenantUser){throw $this->createAccessDeniedException();}$error=null;if($request->isMethod('POST')){if(!$this->isCsrfTokenValid('registries',$request->request->getString('_token'))){throw $this->createAccessDeniedException();}try{match($request->request->getString('action')){'settings'=>$service->updateSettings($user,$request->request->getBoolean('participants'),$request->request->getBoolean('teams'),$request->getClientIp()??''),'organization'=>$service->addOrganization($user,$request->request->getString('name'),$request->request->getString('type'),$request->request->getString('city'),$request->getClientIp()??''),'participant'=>$service->addRegistryParticipant($user,$request->request->all(),$request->getClientIp()??''),'team'=>$service->addRegistryTeam($user,$request->request->all(),$request->getClientIp()??''),default=>throw new \DomainException('Unbekannte Aktion.')};return $this->redirectToRoute('tenant_registries',['slug'=>$context->get()->getSlug()]);}catch(\DomainException $e){$error=$e->getMessage();}}return $this->render('tenant/registries.html.twig',['tenant'=>$context->get(),'data'=>$service->registries($user),'error'=>$error]);}
    #[Route('/v/{slug}/stammdaten/teilnehmer/{id}/loeschen',name:'tenant_registry_participant_delete',methods:['POST'])]
    public function deleteParticipant(string $id,Request $request,TenantContext $context,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser||!$this->isCsrfTokenValid('registry_delete_'.$id,$request->request->getString('_token'))){throw $this->createAccessDeniedException();}try{$service->deleteRegistryParticipant($user,$id,$request->request->getBoolean('anonymize'),$request->getClientIp()??'');}catch(\DomainException $e){$this->addFlash('danger',$e->getMessage());}return $this->redirectToRoute('tenant_registries',['slug'=>$context->get()->getSlug()]);}
    #[Route('/v/{slug}/stammdaten/mannschaft/{id}/loeschen',name:'tenant_registry_team_delete',methods:['POST'])]
    public function deleteTeam(string $id,Request $request,TenantContext $context,ParticipantTeamService $service):Response{$user=$this->getUser();if(!$user instanceof TenantUser||!$this->isCsrfTokenValid('team_registry_delete_'.$id,$request->request->getString('_token'))){throw $this->createAccessDeniedException();}try{$service->deleteRegistryTeam($user,$id,$request->getClientIp()??'');}catch(\DomainException $e){$this->addFlash('danger',$e->getMessage());}return $this->redirectToRoute('tenant_registries',['slug'=>$context->get()->getSlug()]);}
}
