<?php
declare(strict_types=1);
namespace App\Core\Application\Event;

use App\Core\Domain\Tenant\TenantRole;
use App\Core\Infrastructure\Doctrine\Entity\TenantUser;
use App\Core\Infrastructure\Security\AuditLogger;
use App\Core\Infrastructure\Tenancy\EventAccess;
use Doctrine\DBAL\Connection;
use Symfony\Component\Uid\Uuid;

final readonly class ParticipantTeamService
{
    public function __construct(private Connection $connection, private EventAccess $access, private AuditLogger $audit) {}

    /** @return array{settings:array<string,mixed>,organizations:list<array<string,mixed>>,participants:list<array<string,mixed>>,teams:list<array<string,mixed>>} */
    public function registries(TenantUser $actor): array
    {
        $tenant = $actor->getTenant()->getId() ?? throw new \LogicException('Missing tenant id.');
        $settings = $this->connection->fetchAssociative('SELECT participant_registry_enabled, team_registry_enabled FROM tenants WHERE id = :tenant', ['tenant' => $tenant]);
        return ['settings' => $settings === false ? [] : $settings, 'organizations' => $this->connection->fetchAllAssociative('SELECT * FROM external_organizations WHERE tenant_id = :tenant ORDER BY active DESC, name', ['tenant' => $tenant]), 'participants' => $this->connection->fetchAllAssociative('SELECT p.*, o.name AS organization_name FROM participant_registry p LEFT JOIN external_organizations o ON o.id = p.organization_id AND o.tenant_id = p.tenant_id WHERE p.tenant_id = :tenant ORDER BY p.active DESC, p.last_name, p.first_name', ['tenant' => $tenant]), 'teams' => $this->connection->fetchAllAssociative('SELECT t.*, o.name AS organization_name FROM team_registry t LEFT JOIN external_organizations o ON o.id = t.organization_id AND o.tenant_id = t.tenant_id WHERE t.tenant_id = :tenant ORDER BY t.active DESC, t.name', ['tenant' => $tenant])];
    }

    public function updateSettings(TenantUser $actor, bool $participants, bool $teams, string $ip): void { $this->requireAdmin($actor); $this->connection->update('tenants', ['participant_registry_enabled' => $participants, 'team_registry_enabled' => $teams], ['id' => $actor->getTenant()->getId()]); $this->audit->log('registry.settings_changed', 'tenant', $actor->getTenant()->getPublicId(), $actor->getTenant(), $actor, ['participants' => $participants, 'teams' => $teams], $ip); }
    public function addOrganization(TenantUser $actor, string $name, string $type, string $city, string $ip): string { $this->requireAdmin($actor); if (!in_array($type, ['club','school','company','association','other'], true) || trim($name) === '') { throw new \DomainException('Name oder Organisationstyp ist ungültig.'); } $id = Uuid::v7()->toRfc4122(); $now = gmdate('Y-m-d H:i:s'); $this->connection->insert('external_organizations', ['tenant_id' => $actor->getTenant()->getId(), 'public_id' => $id, 'name' => mb_substr(trim($name), 0, 180), 'organization_type' => $type, 'city' => mb_substr(trim($city), 0, 120), 'country_code' => 'CH', 'active' => 1, 'notes' => null, 'created_at' => $now, 'updated_at' => $now, 'lock_version' => 1]); $this->audit->log('organization.created', 'external_organization', $id, $actor->getTenant(), $actor, [], $ip); return $id; }
    /** @param array<string,mixed> $data */
    public function addRegistryParticipant(TenantUser $actor, array $data, string $ip): string { $this->requireAdmin($actor); $id = Uuid::v7()->toRfc4122(); $now = gmdate('Y-m-d H:i:s'); $this->connection->insert('participant_registry', ['tenant_id' => $actor->getTenant()->getId(), 'public_id' => $id, 'organization_id' => $this->organizationId($actor, (string) ($data['organization'] ?? '')), 'first_name' => $this->required($data, 'first_name'), 'last_name' => $this->required($data, 'last_name'), 'birth_date' => null, 'birth_year' => $this->year($data['birth_year'] ?? null), 'gender' => trim((string) ($data['gender'] ?? '')) ?: null, 'city' => trim((string) ($data['city'] ?? '')) ?: null, 'nationality' => null, 'email' => trim((string) ($data['email'] ?? '')) ?: null, 'phone' => trim((string) ($data['phone'] ?? '')) ?: null, 'external_id' => trim((string) ($data['external_id'] ?? '')) ?: null, 'notes' => null, 'active' => 1, 'created_at' => $now, 'updated_at' => $now, 'lock_version' => 1]); $this->audit->log('participant_registry.created', 'participant', $id, $actor->getTenant(), $actor, [], $ip); return $id; }
    /** @param array<string,mixed> $data */
    public function addRegistryTeam(TenantUser $actor, array $data, string $ip): string { $this->requireAdmin($actor); $id = Uuid::v7()->toRfc4122(); $now = gmdate('Y-m-d H:i:s'); $this->connection->insert('team_registry', ['tenant_id' => $actor->getTenant()->getId(), 'public_id' => $id, 'organization_id' => $this->organizationId($actor, (string) ($data['organization'] ?? '')), 'name' => $this->required($data, 'name'), 'category' => trim((string) ($data['category'] ?? '')) ?: null, 'contact_name' => trim((string) ($data['contact_name'] ?? '')) ?: null, 'contact_email' => trim((string) ($data['contact_email'] ?? '')) ?: null, 'contact_phone' => null, 'notes' => null, 'active' => 1, 'created_at' => $now, 'updated_at' => $now, 'lock_version' => 1]); $this->audit->log('team_registry.created', 'team', $id, $actor->getTenant(), $actor, [], $ip); return $id; }

    /** @return array{event:array<string,mixed>,participants:list<array<string,mixed>>,teams:list<array<string,mixed>>,registry:list<array<string,mixed>>} */
    public function roster(TenantUser $actor, string $eventPublicId): array { $event = $this->mutableEvent($actor, $eventPublicId, false); $tenant = (int) $event['tenant_id']; $eventId = (int) $event['id']; return ['event' => $event, 'participants' => $this->connection->fetchAllAssociative('SELECT p.*, t.public_id AS team_public_id, t.name AS team_name FROM event_participants p LEFT JOIN event_team_memberships m ON m.participant_id=p.id AND m.event_id=p.event_id AND m.tenant_id=p.tenant_id LEFT JOIN event_teams t ON t.id=m.team_id AND t.event_id=m.event_id AND t.tenant_id=m.tenant_id WHERE p.tenant_id=:tenant AND p.event_id=:event ORDER BY p.last_name,p.first_name', ['tenant'=>$tenant,'event'=>$eventId]), 'teams' => $this->connection->fetchAllAssociative('SELECT * FROM event_teams WHERE tenant_id=:tenant AND event_id=:event ORDER BY team_number', ['tenant'=>$tenant,'event'=>$eventId]), 'registry' => $this->connection->fetchAllAssociative('SELECT public_id,first_name,last_name,birth_year FROM participant_registry WHERE tenant_id=:tenant AND active=1 ORDER BY last_name,first_name', ['tenant'=>$tenant])]; }
    /** @param array<string,mixed> $data */
    public function addEventParticipant(TenantUser $actor, string $eventPublicId, array $data, string $ip): string { $event = $this->mutableEvent($actor, $eventPublicId); $registry = null; if (($data['registry'] ?? '') !== '') { $registry = $this->connection->fetchAssociative('SELECT p.*, o.name AS organization_name FROM participant_registry p LEFT JOIN external_organizations o ON o.id=p.organization_id AND o.tenant_id=p.tenant_id WHERE p.tenant_id=:tenant AND p.public_id=:id AND p.active=1', ['tenant'=>$event['tenant_id'],'id'=>$data['registry']]); if ($registry === false) { throw new \DomainException('Stammteilnehmer nicht gefunden.'); } } $source = is_array($registry) ? ['first_name'=>$registry['first_name'],'last_name'=>$registry['last_name'],'birth_year'=>$registry['birth_year'],'gender'=>$registry['gender'],'city'=>$registry['city'],'external_id'=>$registry['external_id'],'organization_name'=>$registry['organization_name']] : $data; $id = Uuid::v7()->toRfc4122(); $now=gmdate('Y-m-d H:i:s'); $this->connection->insert('event_participants',['tenant_id'=>$event['tenant_id'],'event_id'=>$event['id'],'registry_participant_id'=>$registry['id']??null,'public_id'=>$id,'first_name'=>$this->required($source,'first_name'),'last_name'=>$this->required($source,'last_name'),'birth_date'=>null,'birth_year'=>$this->year($source['birth_year']??null),'gender'=>trim((string)($source['gender']??''))?:null,'city'=>trim((string)($source['city']??''))?:null,'organization_name'=>trim((string)($source['organization_name']??''))?:null,'external_id'=>trim((string)($source['external_id']??''))?:null,'sport_data'=>json_encode($data['sport_data']??[],JSON_THROW_ON_ERROR),'anonymized_at'=>null,'created_at'=>$now,'updated_at'=>$now,'lock_version'=>1]); $this->audit->log('event.participant_added','event_participant',$id,$actor->getTenant(),$actor,['event'=>$eventPublicId],$ip); return $id; }
    /** @param array<string,mixed> $data */
    public function addEventTeam(TenantUser $actor,string $eventPublicId,array $data,string $ip):string { $event=$this->mutableEvent($actor,$eventPublicId); $id=Uuid::v7()->toRfc4122(); $now=gmdate('Y-m-d H:i:s'); $this->connection->insert('event_teams',['tenant_id'=>$event['tenant_id'],'event_id'=>$event['id'],'registry_team_id'=>null,'public_id'=>$id,'team_number'=>(int)$data['team_number'],'name'=>$this->required($data,'name'),'organization_name'=>null,'category'=>trim((string)($data['category']??''))?:null,'contact_name'=>trim((string)($data['contact_name']??''))?:null,'contact_email'=>trim((string)($data['contact_email']??''))?:null,'contact_phone'=>null,'notes'=>null,'created_at'=>$now,'updated_at'=>$now,'lock_version'=>1]); $this->audit->log('event.team_added','event_team',$id,$actor->getTenant(),$actor,['event'=>$eventPublicId],$ip); return $id; }
    public function assignTeam(TenantUser $actor,string $eventPublicId,string $participantPublicId,string $teamPublicId,string $ip):void { $event=$this->mutableEvent($actor,$eventPublicId); $participant=$this->connection->fetchOne('SELECT id FROM event_participants WHERE tenant_id=:tenant AND event_id=:event AND public_id=:id',['tenant'=>$event['tenant_id'],'event'=>$event['id'],'id'=>$participantPublicId]); $team=$this->connection->fetchOne('SELECT id FROM event_teams WHERE tenant_id=:tenant AND event_id=:event AND public_id=:id',['tenant'=>$event['tenant_id'],'event'=>$event['id'],'id'=>$teamPublicId]); if($participant===false||$team===false){throw new \DomainException('Team oder Teilnehmer nicht gefunden.');} $this->connection->executeStatement('INSERT INTO event_team_memberships (tenant_id,event_id,team_id,participant_id,created_at) VALUES (:tenant,:event,:team,:participant,:now) ON DUPLICATE KEY UPDATE team_id=VALUES(team_id)',['tenant'=>$event['tenant_id'],'event'=>$event['id'],'team'=>$team,'participant'=>$participant,'now'=>gmdate('Y-m-d H:i:s')]); $this->audit->log('event.participant_team_assigned','event_participant',$participantPublicId,$actor->getTenant(),$actor,['event'=>$eventPublicId,'team'=>$teamPublicId],$ip); }
    public function deleteRegistryParticipant(TenantUser $actor,string $publicId,bool $anonymizeHistory,string $ip):void { $this->requireAdmin($actor); $row=$this->connection->fetchAssociative('SELECT id FROM participant_registry WHERE tenant_id=:tenant AND public_id=:id',['tenant'=>$actor->getTenant()->getId(),'id'=>$publicId]); if($row===false){throw new \DomainException('Teilnehmer nicht gefunden.');} if($anonymizeHistory){$this->connection->executeStatement("UPDATE event_participants SET first_name='Anonymisiert',last_name=CONCAT('Teilnehmer ',id),birth_date=NULL,birth_year=NULL,gender=NULL,city=NULL,organization_name=NULL,external_id=NULL,anonymized_at=:now,updated_at=:now,lock_version=lock_version+1 WHERE tenant_id=:tenant AND registry_participant_id=:registry",['now'=>gmdate('Y-m-d H:i:s'),'tenant'=>$actor->getTenant()->getId(),'registry'=>$row['id']]);} $this->connection->delete('participant_registry',['id'=>$row['id'],'tenant_id'=>$actor->getTenant()->getId()]); $this->audit->log('participant_registry.deleted','participant',$publicId,$actor->getTenant(),$actor,['historical_anonymization'=>$anonymizeHistory],$ip); }
    public function deleteRegistryTeam(TenantUser $actor,string $publicId,string $ip):void { $this->requireAdmin($actor); $affected=$this->connection->delete('team_registry',['tenant_id'=>$actor->getTenant()->getId(),'public_id'=>$publicId]); if($affected!==1){throw new \DomainException('Mannschaft nicht gefunden.');}$this->audit->log('team_registry.deleted','team',$publicId,$actor->getTenant(),$actor,['historical_snapshots_retained'=>true],$ip); }
    /** @param array<string,mixed> $row */
    public function importCsvParticipant(TenantUser $actor,string $eventPublicId,array $row,string $strategy,string $ip):bool { if(!in_array($strategy,['skip','new','update'],true)){throw new \DomainException('Ungültige Duplikatstrategie.');}$event=$this->mutableEvent($actor,$eventPublicId);$existing=$this->connection->fetchAssociative('SELECT id,public_id,lock_version FROM event_participants WHERE tenant_id=:tenant AND event_id=:event AND LOWER(first_name)=:first AND LOWER(last_name)=:last AND birth_year=:year ORDER BY id LIMIT 1',['tenant'=>$event['tenant_id'],'event'=>$event['id'],'first'=>mb_strtolower(trim((string)($row['Vorname']??''))),'last'=>mb_strtolower(trim((string)($row['Nachname']??''))),'year'=>$this->year($row['Geburtsjahr']??null)]);if($existing!==false&&$strategy==='skip'){return false;}if($existing!==false&&$strategy==='update'){$this->connection->update('event_participants',['gender'=>trim((string)($row['Geschlecht']??''))?:null,'city'=>trim((string)($row['Ort']??''))?:null,'external_id'=>trim((string)($row['Externe ID']??''))?:null,'sport_data'=>json_encode(['school_class'=>$row['Schulklasse']??''],JSON_THROW_ON_ERROR),'updated_at'=>gmdate('Y-m-d H:i:s'),'lock_version'=>(int)$existing['lock_version']+1],['tenant_id'=>$event['tenant_id'],'event_id'=>$event['id'],'id'=>$existing['id'],'lock_version'=>$existing['lock_version']]);$this->audit->log('event.participant_csv_updated','event_participant',(string)$existing['public_id'],$actor->getTenant(),$actor,['event'=>$eventPublicId],$ip);return true;}$this->addEventParticipant($actor,$eventPublicId,['first_name'=>$row['Vorname']??'','last_name'=>$row['Nachname']??'','birth_year'=>$row['Geburtsjahr']??null,'gender'=>$row['Geschlecht']??'','city'=>$row['Ort']??'','external_id'=>$row['Externe ID']??'','sport_data'=>['school_class'=>$row['Schulklasse']??'']],$ip);return true;}
    /** @return array<string,mixed> */ private function mutableEvent(TenantUser $actor,string $publicId,bool $write=true):array { if(($write&&!$this->access->canEnterData($actor,$publicId))||(!$write&&!$this->access->canRead($actor,$publicId))){throw new \DomainException('Keine Berechtigung.');} $row=$this->connection->fetchAssociative('SELECT id,tenant_id,public_id,name,status FROM events WHERE tenant_id=:tenant AND public_id=:id',['tenant'=>$actor->getTenant()->getId(),'id'=>$publicId]); if($row===false){throw new \DomainException('Veranstaltung nicht gefunden.');} if($write&&in_array($row['status'],['completed','cancelled','archived'],true)){throw new \DomainException('Diese Veranstaltung ist nicht mehr bearbeitbar.');} return $row; }
    /** @param array<string,mixed> $data */ private function required(array $data,string $key):string{$value=trim((string)($data[$key]??''));if($value===''){throw new \DomainException('Pflichtfeld fehlt: '.$key);}return mb_substr($value,0,180);} private function year(mixed $value):?int{$year=(int)$value;if($year===0){return null;}if($year<1900||$year>(int)gmdate('Y')){throw new \DomainException('Geburtsjahr ist ungültig.');}return $year;} private function organizationId(TenantUser $actor,string $publicId):?int{if($publicId===''){return null;}$id=$this->connection->fetchOne('SELECT id FROM external_organizations WHERE tenant_id=:tenant AND public_id=:id AND active=1',['tenant'=>$actor->getTenant()->getId(),'id'=>$publicId]);return $id===false?throw new \DomainException('Organisation nicht gefunden.'):(int)$id;} private function requireAdmin(TenantUser $actor):void{if(!in_array($actor->getTenantRole(),[TenantRole::Owner,TenantRole::Administrator],true)){throw new \DomainException('Nur Owner oder Administratoren dürfen Vereinsstämme verwalten.');}}
}
